/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spacellama;

/**
 *
 * @author Laura
 */
public class infoLibros {
    public String[] informacion = new String [8];
    public infoLibros() {
        informacion[0] = "1Es el planeta mas próximo al sol y el mas pequeño, forma parte de los planetas interiores o terrestres, carece de satélites. Tiene cuerpo rocoso, formado por 70% de elementos metálicos y un 30% de silicatos. La densidad de este planeta es la segunda más grande de todo el sistema solar. Se estima que su núcleo ocupa un 42% de su volumen total. ¿Sabías que Mercurio es el planeta más caliente del sistema solar? Esto se debe a que se encuentra a una muy corta distancia del Sol y también por esto es que su núcleo de magma ocupa el 42% de su volumen total.";
        informacion[1] = "2Es el planeta mas próximo al sol y el mas pequeño, forma parte de los planetas interiores o terrestres, carece de satélites. Tiene cuerpo rocoso, formado por 70% de elementos metálicos y un 30% de silicatos. La densidad de este planeta es la segunda más grande de todo el sistema solar. Se estima que su núcleo ocupa un 42% de su volumen total. ¿Sabías que Mercurio es el planeta más caliente del sistema solar? Esto se debe a que se encuentra a una muy corta distancia del Sol y también por esto es que su núcleo de magma ocupa el 42% de su volumen total.";
        informacion[2] = "3Es el planeta mas próximo al sol y el mas pequeño, forma parte de los planetas interiores o terrestres, carece de satélites. Tiene cuerpo rocoso, formado por 70% de elementos metálicos y un 30% de silicatos. La densidad de este planeta es la segunda más grande de todo el sistema solar. Se estima que su núcleo ocupa un 42% de su volumen total. ¿Sabías que Mercurio es el planeta más caliente del sistema solar? Esto se debe a que se encuentra a una muy corta distancia del Sol y también por esto es que su núcleo de magma ocupa el 42% de su volumen total.";
        informacion[3] = "4Es el planeta mas próximo al sol y el mas pequeño, forma parte de los planetas interiores o terrestres, carece de satélites. Tiene cuerpo rocoso, formado por 70% de elementos metálicos y un 30% de silicatos. La densidad de este planeta es la segunda más grande de todo el sistema solar. Se estima que su núcleo ocupa un 42% de su volumen total. ¿Sabías que Mercurio es el planeta más caliente del sistema solar? Esto se debe a que se encuentra a una muy corta distancia del Sol y también por esto es que su núcleo de magma ocupa el 42% de su volumen total.";
        informacion[4] = "5Es el planeta mas próximo al sol y el mas pequeño, forma parte de los planetas interiores o terrestres, carece de satélites. Tiene cuerpo rocoso, formado por 70% de elementos metálicos y un 30% de silicatos. La densidad de este planeta es la segunda más grande de todo el sistema solar. Se estima que su núcleo ocupa un 42% de su volumen total. ¿Sabías que Mercurio es el planeta más caliente del sistema solar? Esto se debe a que se encuentra a una muy corta distancia del Sol y también por esto es que su núcleo de magma ocupa el 42% de su volumen total.";
        informacion[5] = "6Es el planeta mas próximo al sol y el mas pequeño, forma parte de los planetas interiores o terrestres, carece de satélites. Tiene cuerpo rocoso, formado por 70% de elementos metálicos y un 30% de silicatos. La densidad de este planeta es la segunda más grande de todo el sistema solar. Se estima que su núcleo ocupa un 42% de su volumen total. ¿Sabías que Mercurio es el planeta más caliente del sistema solar? Esto se debe a que se encuentra a una muy corta distancia del Sol y también por esto es que su núcleo de magma ocupa el 42% de su volumen total.";
        informacion[6] = "7Es el planeta mas próximo al sol y el mas pequeño, forma parte de los planetas interiores o terrestres, carece de satélites. Tiene cuerpo rocoso, formado por 70% de elementos metálicos y un 30% de silicatos. La densidad de este planeta es la segunda más grande de todo el sistema solar. Se estima que su núcleo ocupa un 42% de su volumen total. ¿Sabías que Mercurio es el planeta más caliente del sistema solar? Esto se debe a que se encuentra a una muy corta distancia del Sol y también por esto es que su núcleo de magma ocupa el 42% de su volumen total.";
        informacion[7] = "8Es el planeta mas próximo al sol y el mas pequeño, forma parte de los planetas interiores o terrestres, carece de satélites. Tiene cuerpo rocoso, formado por 70% de elementos metálicos y un 30% de silicatos. La densidad de este planeta es la segunda más grande de todo el sistema solar. Se estima que su núcleo ocupa un 42% de su volumen total. ¿Sabías que Mercurio es el planeta más caliente del sistema solar? Esto se debe a que se encuentra a una muy corta distancia del Sol y también por esto es que su núcleo de magma ocupa el 42% de su volumen total.";
    }
}
